version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/daata
    restart: always

volumes:
  pg-data:
