spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/tps
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    async:
      request-timeout: 600000 # 10 minutes
  application:
    name: external-system

logging:
  level:
    org:
      springframework:
        cache: TRACE

management:
  metrics:
    tags:
      service: external-system
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,metrics"

logstash:
  url: logstash:4560

auth:
  token: strong